### ISSUE TITLE
Where should be the right place I set the seed?

### ISSUE THREAD

**Issue by sherlock1987** [ConvLab/ConvLab#116]
Hello, guys, recently I am going to set seed so that my results could be reproductive. And I am going to set the seed for rule_wdqn or rule_ppo for policy training. Is there any clue where should I set the seed?

**Comment by jincli** [comment]
@sherlock1987  Please check line 64 of https://github.com/ConvLab/ConvLab/blob/master/convlab/experiment/control.py

**Comment by sherlock1987** [comment]
You are right, simply put these code to line 62. And it will be all set.

        seed = 1
        torch.manual_seed(seed)
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        np.random.seed(seed)  # Numpy module.
        random.seed(seed)  # Python random module.
        torch.manual_seed(seed)
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True

**Comment by sherlock1987** [comment]
And I have another question, hope you could help me. This is about evaluation, I find that evenif I set seed for the code, and the loss and total reward stays the same. But evaluation is different, eg, the first time avg_success is 0.08, the second time avg_success is 0.1. Could you give me some cluse? Thank you so much!

**Comment by zqwerty** [comment]
> And I have another question, hope you could help me. This is about evaluation, I find that evenif I set seed for the code, and the loss and total reward stays the same. But evaluation is different, eg, the first time avg_success is 0.08, the second time avg_success is 0.1. Could you give me some cluse? Thank you so much!

This may be caused by the undefined behavior (item order) of turning a `set` to a `list`. You can try to replace https://github.com/ConvLab/ConvLab/blob/master/convlab/modules/policy/user/multiwoz/policy_agenda_multiwoz.py#L200 to `value_list = sorted(list(set(value_list)|set(low_value_list)))` (which is fixed in ConvLab-2)

**Comment by sherlock1987** [comment]
Hey, it is not working, I change the code like what you said, is that possible that elevator is a seperate part from run.py? If yes, I think set seed again to elevator will  give me some answers.

**Comment by jincli** [comment]
@sherlock1987  Probably you can further check whether the generated goals are the same for all your runs.

**Comment by sherlock1987** [comment]
I do a lot exp recently, but I still fail to get the seed for eval. Anyway, I find that I could set the num_eval = 1000, and the eval results change a little (around 0.001).

**Comment by sherlock1987** [comment]
Hey, guys, to the start I set the seed in /convlab/lib/util.py, but this is actually not working. Since I make the same seed for this function, and the learning curve is totally different. The function I am talking is set_random_seed(). And I think this is a potential bugs.
